# Data Preprocessing for Machine Learning

## Objective

Prepare the feature-engineered dataset for machine learning by selecting appropriate input features, encoding categorical variables, scaling numerical features where necessary, and creating training and testing datasets for model development.

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

import joblib

# Load Feature Engineered Dataset

## Objective

Load the feature-engineered dataset that will be used for machine learning preprocessing.

In [ ]:
df = pd.read_csv("../data/employee_attrition_feature_engineered.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,IncomeGroup,ExperienceGroup,PromotionDelay,DistanceCategory,OverallSatisfaction,TenureGroup
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,6,4,0,5,High,Mid Career,Recently Promoted,Near,8,Experienced
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,10,7,1,7,High,Mid Career,Recently Promoted,Moderate,12,Experienced
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,0,0,0,0,Low,Mid Career,Recently Promoted,Near,12,NaN
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,8,7,3,0,Low,Mid Career,Moderate Delay,Near,13,Experienced
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,2,2,2,2,Medium,Mid Career,Moderate Delay,Near,10,New

# Dataset Inspection

## Objective

Inspect the dataset to verify its structure, dimensions, data types, and ensure that all engineered features have been created successfully before preprocessing.

In [ ]:
print("Dataset Shape :", df.shape)

Dataset Shape : (1470, 38)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   object
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   object
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  OverTime                  1470 non-null   object
 21  PercentSalaryHike         1470 non-null   int64
 22  PerformanceRating         1470 non-null   int64
 23  RelationshipSatisfaction  1470 non-null   int64
 24  StockOptionLevel          1470 non-null   int64
 25  TotalWorkingYears         1470 non-null   int64
 26  TrainingTimesLastYear     1470 non-null   int64
 27  WorkLifeBalance           1470 non-null   int64
 28  YearsAtCompany            1470 non-null   int64
 29  YearsInCurrentRole        1470 non-null   int64
 30  YearsSinceLastPromotion   1470 non-null   int64
 31  YearsWithCurrManager      1470 non-null   int64
 32  IncomeGroup               1470 non-null   object
 33  ExperienceGroup           1459 non-null   object
 34  PromotionDelay            1470 non-null   object
 35  DistanceCategory          1470 non-null   object
 36  OverallSatisfaction       1470 non-null   int64
 37  TenureGroup               1426 non-null   object
dtypes: int64(25), object(13)
memory usage: 436.5+ KB

In [ ]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
IncomeGroup                 object
ExperienceGroup             object
PromotionDelay              object
DistanceCategory            object
OverallSatisfaction          int64
TenureGroup                 object
dtype: object

In [ ]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,IncomeGroup,ExperienceGroup,PromotionDelay,DistanceCategory,OverallSatisfaction,TenureGroup
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,6,4,0,5,High,Mid Career,Recently Promoted,Near,8,Experienced
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,10,7,1,7,High,Mid Career,Recently Promoted,Moderate,12,Experienced
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,0,0,0,0,Low,Mid Career,Recently Promoted,Near,12,NaN
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,8,7,3,0,Low,Mid Career,Moderate Delay,Near,13,Experienced
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,2,2,2,2,Medium,Mid Career,Moderate Delay,Near,10,New

### Observation

- The feature-engineered dataset has been loaded successfully.
- The dataset contains both numerical and categorical variables.
- Newly engineered features are present and ready for preprocessing.

# Identify the Target Variable

## Objective

Select the target variable that the machine learning models will learn to predict.

In [ ]:
df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

### Explanation

The **Attrition** column is selected as the target variable because it indicates whether an employee has left the organization. Machine learning models will use the remaining variables to predict this outcome.

# Evaluate Features for Machine Learning

## Objective

Review the available features and identify any columns that do not provide meaningful predictive information.

In [ ]:
df.columns.tolist()

['Age',
 'Attrition',
 'BusinessTravel',
 'DailyRate',
 'Department',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager',
 'IncomeGroup',
 'ExperienceGroup',
 'PromotionDelay',
 'DistanceCategory',
 'OverallSatisfaction',
 'TenureGroup']

# Evaluate Features for Machine Learning

## Objective

Before preparing the dataset for machine learning, each feature is evaluated to determine whether it provides useful predictive information.

Identifier columns are removed because they uniquely identify employees rather than describe their characteristics. Such columns do not help the model learn patterns related to employee attrition and may introduce unnecessary noise.

The cleaned dataset created in the previous notebooks has already removed constant and irrelevant columns. Therefore, only the remaining identifier column is removed in this step.

In [ ]:
# Remove identifier column
df = df.drop(columns=["EmployeeNumber"], errors="ignore")

# Verify the updated dataset
df.shape

(1470, 37)

### Observation

The **EmployeeNumber** column has been removed because it serves only as a unique identifier and does not contribute to predicting employee attrition.

The dataset now contains only meaningful employee attributes that can be used for machine learning.

# Separate Features and Target

## Objective

Machine learning requires separating the dataset into:

- **Input Features (X):** Variables used to predict employee attrition.
- **Target Variable (y):** The outcome that the model will learn to predict.

In this project, **Attrition** is selected as the target variable, while all remaining columns serve as input features.

In [ ]:
# Separate features and target

X = df.drop(columns=["Attrition"])
y = df["Attrition"]

print("Feature matrix shape:", X.shape)
print("Target vector shape:", y.shape)

Feature matrix shape: (1470, 36)
Target vector shape: (1470,)

In [ ]:
X.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,IncomeGroup,ExperienceGroup,PromotionDelay,DistanceCategory,OverallSatisfaction,TenureGroup
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,94,...,6,4,0,5,High,Mid Career,Recently Promoted,Near,8,Experienced
1,49,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,61,...,10,7,1,7,High,Mid Career,Recently Promoted,Moderate,12,Experienced
2,37,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,92,...,0,0,0,0,Low,Mid Career,Recently Promoted,Near,12,NaN
3,33,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,56,...,8,7,3,0,Low,Mid Career,Moderate Delay,Near,13,Experienced
4,27,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,40,...,2,2,2,2,Medium,Mid Career,Moderate Delay,Near,10,New

In [ ]:
y.head()

0    Yes
1     No
2    Yes
3     No
4     No
Name: Attrition, dtype: object

### Observation

The dataset has been successfully divided into input features (**X**) and the target variable (**y**).

- **X** contains all employee attributes that will be used for prediction.
- **y** contains the employee attrition status that the machine learning models will learn to classify.

# Encode the Target Variable

## Objective

Machine learning algorithms require numerical target values rather than text labels.

The target variable **Attrition** currently contains two categories:

- **Yes** – Employee left the company
- **No** – Employee stayed with the company

Since this is a binary classification problem, label encoding is appropriate.

The categories will be encoded as:

- **Yes → 1**
- **No → 0**

In [ ]:
# Encode target variable

y = y.map({
    "No": 0,
    "Yes": 1
})

y.head()

0    1
1    0
2    1
3    0
4    0
Name: Attrition, dtype: int64

In [ ]:
# Verify target encoding

y.value_counts()

Attrition
0    1233
1     237
Name: count, dtype: int64

### Observation

The target variable has been successfully converted into numerical values.

- **0** represents employees who stayed with the company.
- **1** represents employees who left the company.

This format is suitable for binary classification algorithms.

# Identify Numerical and Categorical Features

## Objective

Different preprocessing techniques are required for numerical and categorical variables.

- **Numerical features** will later be scaled when required.
- **Categorical features** must be encoded before they can be used by machine learning algorithms.

Separating these feature types helps apply the appropriate preprocessing methods efficiently.

In [ ]:
# Identify numerical and categorical columns

numerical_features = X.select_dtypes(include=["int64", "float64"]).columns.tolist()

categorical_features = X.select_dtypes(include=["object", "category"]).columns.tolist()

print("Number of Numerical Features:", len(numerical_features))
print("Number of Categorical Features:", len(categorical_features))

Number of Numerical Features: 24
Number of Categorical Features: 12

In [ ]:
print("Numerical Features:\n")
print(numerical_features)

Numerical Features:

['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager', 'OverallSatisfaction']

In [ ]:
print("Categorical Features:\n")
print(categorical_features)

Categorical Features:

['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime', 'IncomeGroup', 'ExperienceGroup', 'PromotionDelay', 'DistanceCategory', 'TenureGroup']

### Observation

The dataset has been divided into numerical and categorical feature groups.

- **Numerical features** represent measurable employee attributes such as age, income, experience, and distance from home.
- **Categorical features** represent employee classifications such as department, job role, business travel, and the engineered category-based features.

This separation ensures that the appropriate preprocessing techniques can be applied in the following steps.

# Encode Categorical Features

## Objective

Machine learning algorithms cannot directly process text-based categorical variables.

Therefore, categorical features are converted into numerical representations using **One-Hot Encoding**.

One-Hot Encoding creates a separate binary column for each category without introducing any artificial ordering between categories, making it suitable for nominal variables.

In [ ]:
# Display categorical features

categorical_features

['BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'OverTime',
 'IncomeGroup',
 'ExperienceGroup',
 'PromotionDelay',
 'DistanceCategory',
 'TenureGroup']

The following categorical features will be encoded using One-Hot Encoding.

This includes both original categorical variables and the engineered categorical features created during feature engineering.

In [ ]:
# Apply One-Hot Encoding

X_encoded = pd.get_dummies(
    X,
    columns=categorical_features,
    drop_first=True,
    dtype=int
)

In [ ]:
# Display encoded dataset

X_encoded.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,ExperienceGroup_Mid Career,ExperienceGroup_Senior,PromotionDelay_Moderate Delay,PromotionDelay_Recently Promoted,PromotionDelay_Very Long Delay,DistanceCategory_Moderate,DistanceCategory_Near,TenureGroup_Junior,TenureGroup_New,TenureGroup_Veteran
0,41,1102,1,2,2,94,3,2,4,5993,...,1,0,0,1,0,0,1,0,0,0
1,49,279,8,1,3,61,2,2,2,5130,...,1,0,0,1,0,1,0,0,0,0
2,37,1373,2,2,4,92,2,1,3,2090,...,1,0,0,1,0,0,1,0,0,0
3,33,1392,3,4,4,56,3,1,3,2909,...,1,0,1,0,0,0,1,0,0,0
4,27,591,2,1,1,40,3,1,2,3468,...,1,0,1,0,0,0,1,0,1,0

In [ ]:
print("Original Number of Features :", X.shape[1])
print("Encoded Number of Features  :", X_encoded.shape[1])

Original Number of Features : 36
Encoded Number of Features  : 59

In [ ]:
# Check remaining data types

X_encoded.dtypes.value_counts()

int64    59
Name: count, dtype: int64

In [ ]:
# Verify that no object columns remain

X_encoded.select_dtypes(include="object").columns

Index([], dtype='object')

### Observation

All categorical variables have been successfully converted into numerical features using One-Hot Encoding.

The number of input features has increased because each category is represented by its own binary column.

No object data types remain in the feature matrix, confirming that the dataset is now suitable for machine learning algorithms.

# Verify Encoded Dataset

## Objective

Inspect the encoded feature matrix to ensure that the preprocessing step has been completed successfully before splitting the data into training and testing sets.

In [ ]:
X_encoded.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,ExperienceGroup_Mid Career,ExperienceGroup_Senior,PromotionDelay_Moderate Delay,PromotionDelay_Recently Promoted,PromotionDelay_Very Long Delay,DistanceCategory_Moderate,DistanceCategory_Near,TenureGroup_Junior,TenureGroup_New,TenureGroup_Veteran
0,41,1102,1,2,2,94,3,2,4,5993,...,1,0,0,1,0,0,1,0,0,0
1,49,279,8,1,3,61,2,2,2,5130,...,1,0,0,1,0,1,0,0,0,0
2,37,1373,2,2,4,92,2,1,3,2090,...,1,0,0,1,0,0,1,0,0,0
3,33,1392,3,4,4,56,3,1,3,2909,...,1,0,1,0,0,0,1,0,0,0
4,27,591,2,1,1,40,3,1,2,3468,...,1,0,1,0,0,0,1,0,1,0

In [ ]:
X_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 59 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Age                                 1470 non-null   int64
 1   DailyRate                           1470 non-null   int64
 2   DistanceFromHome                    1470 non-null   int64
 3   Education                           1470 non-null   int64
 4   EnvironmentSatisfaction             1470 non-null   int64
 5   HourlyRate                          1470 non-null   int64
 6   JobInvolvement                      1470 non-null   int64
 7   JobLevel                            1470 non-null   int64
 8   JobSatisfaction                     1470 non-null   int64
 9   MonthlyIncome                       1470 non-null   int64
 10  MonthlyRate                         1470 non-null   int64
 11  NumCompaniesWorked                  1470 non-null   int64
 12  PercentSalaryHike                   1470 non-null   int64
 13  PerformanceRating                   1470 non-null   int64
 14  RelationshipSatisfaction            1470 non-null   int64
 15  StockOptionLevel                    1470 non-null   int64
 16  TotalWorkingYears                   1470 non-null   int64
 17  TrainingTimesLastYear               1470 non-null   int64
 18  WorkLifeBalance                     1470 non-null   int64
 19  YearsAtCompany                      1470 non-null   int64
 20  YearsInCurrentRole                  1470 non-null   int64
 21  YearsSinceLastPromotion             1470 non-null   int64
 22  YearsWithCurrManager                1470 non-null   int64
 23  OverallSatisfaction                 1470 non-null   int64
 24  BusinessTravel_Travel_Frequently    1470 non-null   int64
 25  BusinessTravel_Travel_Rarely        1470 non-null   int64
 26  Department_Research & Development   1470 non-null   int64
 27  Department_Sales                    1470 non-null   int64
 28  EducationField_Life Sciences        1470 non-null   int64
 29  EducationField_Marketing            1470 non-null   int64
 30  EducationField_Medical              1470 non-null   int64
 31  EducationField_Other                1470 non-null   int64
 32  EducationField_Technical Degree     1470 non-null   int64
 33  Gender_Male                         1470 non-null   int64
 34  JobRole_Human Resources             1470 non-null   int64
 35  JobRole_Laboratory Technician       1470 non-null   int64
 36  JobRole_Manager                     1470 non-null   int64
 37  JobRole_Manufacturing Director      1470 non-null   int64
 38  JobRole_Research Director           1470 non-null   int64
 39  JobRole_Research Scientist          1470 non-null   int64
 40  JobRole_Sales Executive             1470 non-null   int64
 41  JobRole_Sales Representative        1470 non-null   int64
 42  MaritalStatus_Married               1470 non-null   int64
 43  MaritalStatus_Single                1470 non-null   int64
 44  OverTime_Yes                        1470 non-null   int64
 45  IncomeGroup_Low                     1470 non-null   int64
 46  IncomeGroup_Medium                  1470 non-null   int64
 47  IncomeGroup_Very High               1470 non-null   int64
 48  ExperienceGroup_Highly Experienced  1470 non-null   int64
 49  ExperienceGroup_Mid Career          1470 non-null   int64
 50  ExperienceGroup_Senior              1470 non-null   int64
 51  PromotionDelay_Moderate Delay       1470 non-null   int64
 52  PromotionDelay_Recently Promoted    1470 non-null   int64
 53  PromotionDelay_Very Long Delay      1470 non-null   int64
 54  DistanceCategory_Moderate           1470 non-null   int64
 55  DistanceCategory_Near               1470 non-null   int64
 56  TenureGroup_Junior                  1470 non-null   int64
 57  TenureGroup_New                     1470 non-null   int64
 58  TenureGroup_Veteran                 1470 non-null   int64
dtypes: int64(59)
memory usage: 677.7 KB

### Observation

The encoded feature matrix contains only numerical variables and is now fully prepared for train-test splitting and feature scaling.

# Split the Dataset into Training and Testing Sets

## Objective

Split the dataset into separate training and testing sets.

- The **training set** is used to train machine learning models.
- The **testing set** is used to evaluate model performance on unseen data.

An **80:20 split** is used, and **stratified sampling** ensures that the proportion of attrition classes remains consistent in both datasets.

In [ ]:
# Split dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [ ]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (1176, 59)
Testing Features  : (294, 59)
Training Labels   : (1176,)
Testing Labels    : (294,)

### Observation

The dataset has been successfully divided into training and testing sets.

Approximately **80%** of the data will be used for model training, while the remaining **20%** will be reserved for evaluating model performance on unseen data.

# Scale Numerical Features

## Objective

Many machine learning algorithms perform better when numerical features are on a similar scale.

Examples include:

- Logistic Regression
- Support Vector Machine (SVM)
- K-Nearest Neighbors (KNN)

Tree-based models such as Decision Trees and Random Forests do not require feature scaling.

To support both types of algorithms, scaled and unscaled datasets will be maintained.

In [ ]:
# Initialize StandardScaler

scaler = StandardScaler()

In [ ]:
# Create copies for scaling

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

In [ ]:
# Identify numerical columns after encoding

numerical_columns = numerical_features

In [ ]:
# Fit scaler on training data and transform

X_train_scaled[numerical_columns] = scaler.fit_transform(
    X_train[numerical_columns]
)

In [ ]:
# Transform testing data

X_test_scaled[numerical_columns] = scaler.transform(
    X_test[numerical_columns]
)

In [ ]:
# Display scaled training data

X_train_scaled.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,ExperienceGroup_Mid Career,ExperienceGroup_Senior,PromotionDelay_Moderate Delay,PromotionDelay_Recently Promoted,PromotionDelay_Very Long Delay,DistanceCategory_Moderate,DistanceCategory_Near,TenureGroup_Junior,TenureGroup_New,TenureGroup_Veteran
1194,1.090194,1.049455,-0.899915,1.064209,-0.658710,-0.908436,1.795282,1.762189,-0.647997,2.026752,...,0,0,0,1,0,0,1,1,0,0
128,-1.634828,-0.523449,-0.899915,-1.855332,0.260202,1.694111,0.373564,-0.986265,1.153526,-0.864408,...,0,0,1,0,0,0,1,0,1,0
810,0.981193,-0.992080,-0.777610,-1.855332,-1.577622,-0.662913,0.373564,1.762189,0.252765,2.347706,...,0,0,0,0,0,0,1,0,0,1
478,-1.307825,-0.453653,0.445433,-1.855332,-0.658710,-1.252169,0.373564,-0.986265,0.252765,-0.956202,...,1,0,0,1,0,1,0,0,0,0
491,0.654191,0.491086,-0.043784,2.037390,1.179114,0.319180,0.373564,-0.070114,0.252765,-0.185956,...,1,0,0,0,0,1,0,0,0,0

### Observation

Only the numerical features have been standardized using **StandardScaler**.

The scaler was fitted **only on the training data** and then applied to the testing data, preventing data leakage and ensuring a fair evaluation of machine learning models.

# Verify Target Distribution

## Objective

Verify that stratified sampling has preserved the class distribution of the target variable in both the training and testing datasets.

In [ ]:
print("Training Target Distribution")

print(y_train.value_counts(normalize=True) * 100)

Training Target Distribution
Attrition
0    83.843537
1    16.156463
Name: proportion, dtype: float64

In [ ]:
print("Testing Target Distribution")

print(y_test.value_counts(normalize=True) * 100)

Testing Target Distribution
Attrition
0    84.013605
1    15.986395
Name: proportion, dtype: float64

### Observation

The class distribution remains nearly identical in both the training and testing datasets, confirming that stratified sampling has been applied successfully.

# Save Preprocessing Objects

## Objective

Save the preprocessing objects for reuse during model evaluation and deployment.

Using the same preprocessing objects during prediction ensures consistency between training and inference.

In [ ]:
# Save scaler

joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']

In [ ]:
# Save feature names

joblib.dump(
    X_encoded.columns.tolist(),
    "../models/feature_names.pkl"
)

['../models/feature_names.pkl']

# Save Processed Datasets

## Objective

Save the processed datasets to support reproducibility and simplify future model development.

In [ ]:
X_train.to_csv("../data/X_train.csv", index=False)
X_test.to_csv("../data/X_test.csv", index=False)

X_train_scaled.to_csv("../data/X_train_scaled.csv", index=False)
X_test_scaled.to_csv("../data/X_test_scaled.csv", index=False)

y_train.to_csv("../data/y_train.csv", index=False)
y_test.to_csv("../data/y_test.csv", index=False)

# Preprocessing Summary

## Summary

The following preprocessing steps were completed successfully:

- Loaded the feature-engineered dataset.
- Removed non-predictive identifier columns.
- Separated the dataset into input features (**X**) and target (**y**).
- Encoded the binary target variable using label encoding.
- Applied One-Hot Encoding to categorical features.
- Split the dataset into stratified training and testing sets.
- Standardized numerical features while preserving unscaled versions.
- Saved the scaler and processed datasets for future model development.

The dataset is now fully prepared for machine learning model training and evaluation.